name: OPS
favicon: null
layout_spectrum: 0.25192
typography_spectrum: 0.50193
title: Operations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d282a'
    - '#ecebe7'
    - '#9fb0bd'
    - '#567488'
    - '#933440'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
